version: '2.1'

services:
  auth-microservice:
    image: auth-microservice
    container_name: auth-microservice
    volumes:
      - .:/usr/src/app
    networks:
      - network
    depends_on:
      - db
      - cache
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  db:
    image: mysql:8.0
    container_name: auth-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: auth-db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: auth-phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - network
  cache:
    image: redis
    container_name: auth-cache
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    networks:
      - network

networks:
  network:
    driver: bridge
