name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run test:setup
          npm test
        env:
          CI: true
          PORT: 3000
          JWT_ACCESS_TOKEN_EXPIRE: 1h
          JWT_REFRESH_TOKEN_EXPIRE: 7d
          JWT_REFRESH_TOKEN_COOKIE_KEY: jid
          PASSWORD_RESET_CODE_EXPIRE_IN_SECONDS: 900
          SMTP_USER: example@mail.com
          RATE_LIMIT_COUNT: 20
          RATE_LIMIT_WINDOW_IN_SECONDS: 300
